### ISSUE TITLE
stuck in start-up loop after crash

### ISSUE THREAD

**Issue by saqebakhter** [thejinx0r/node-gdrive-fuse#69] opened 2015-08-09 17:01 UTC
After crash from too many files open.

Console Log: http://paste.ubuntu.com/12040739/
Debug log: http://pastebin.com/k8L5jKqm

2015-8-9T12:26::6 - ^[[31merror^[[39m:  code=ECONNRESET, errno=ECONNRESET, syscall=read
2015-8-9T12:28::37 - ^[[31merror^[[39m: error after piping code=EMFILE, errno=EMFILE, syscall=connect, address=216.58.216.202, port=443
2015-8-9T12:28::37 - ^[[31merror^[[39m:  code=EMFILE, errno=EMFILE, syscall=connect, address=216.58.216.202, port=443
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: EMFILE: too many open files, open '/mnt/2TB1/cache/upload/f7c08ad629c5f0274f5143e3b8f3fb43'
  at Error (native)

Stuck in start up loop now:

2015-8-9T12:28::55 - ^[[32minfo^[[39m: mount point: /mnt/2TB2/gdrivefs
2015-8-9T12:29::3 - ^[[32minfo^[[39m: resuming file uploading
/mnt/2TB3/sources/node-gdrive-fuse/src/fs.coffee:906
              inodeTree.set(key, value);
                            ^
ReferenceError: key is not defined
  at HashMap.<anonymous> (/mnt/2TB3/sources/node-gdrive-fuse/src/fs.coffee:893:27)
  at HashMap.forEach (/mnt/2TB3/sources/node-gdrive-fuse/node_modules/hashmap/hashmap.js:123:10)
  at [object Object].resumeUpload [as _onTimeout] (/mnt/2TB3/sources/node-gdrive-fuse/src/fs.coffee:877:16)
  at Timer.listOnTimeout (timers.js:89:15)

                                                                                                                                                             616,0-1       46%
  at Timer.listOnTimeout (timers.js:89:15)

stdin: is not a tty
node: no process found
2015-8-9T12:29::6 - ^[[32minfo^[[39m: loading upload tree

**Comment by thejinx0r** [comment] 2015-08-09 18:43
duplicate of #68

**Closed by thejinx0r** 2015-08-09 18:43 UTC
