### ISSUE TITLE
Stability issue - random - TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by ecchi** [thejinx0r/node-gdrive-fuse#42] opened 2015-01-06 22:54 UTC
Pulled f3a6c64b15
Did the usual, deleted cache. At random intervals Issue #37 shows up during media playback.
Mac 10.10.1, node 0.10.35
No additional errors precede or identify the cause. 

Turned on debug, this about the only difference:
```
2015-1-6T17:51::50 - debug: Getting changes from Google Drive. The last change id was 249091.
2015-1-6T17:51::51 - debug: There was 1 to parse
```
until the error kicked in:

```
TypeError: Cannot read property 'id' of undefined
  at parseChanges (/Users/ecchi/Code/node-gdrive-fuse/src/client.coffee:326:32)
  at callback (/Users/ecchi/Code/node-gdrive-fuse/src/client.coffee:279:7)
  at /Users/ecchi/Code/node-gdrive-fuse/src/client.coffee:260:7
  at Request._callback (/Users/ecchi/Code/node-gdrive-fuse/node_modules/googleapis/lib/transporters.js:90:7)
  at Request.self.callback (/Users/ecchi/Code/node-gdrive-fuse/node_modules/googleapis/node_modules/request/request.js:372:22)
  at Request.emit (events.js:98:17)
  at Request.<anonymous> (/Users/ecchi/Code/node-gdrive-fuse/node_modules/googleapis/node_modules/request/request.js:1317:14)
  at Request.emit (events.js:117:20)
  at IncomingMessage.<anonymous> (/Users/ecchi/Code/node-gdrive-fuse/node_modules/googleapis/node_modules/request/request.js:1265:12)
  at IncomingMessage.emit (events.js:117:20)
  at _stream_readable.js:944:16
  at process._tickCallback (node.js:442:13)
```

Anything to suggest changing? Different versions to test with, or commands?

**Comment by ecchi** [comment] 2015-01-07 01:36
Does not even require browsing or accessing files. It eventually produces this error on its own. Looks like 1 min or so intervals. Doing some sort of interval refresh with google?

**Comment by thejinx0r** [comment] 2015-01-07 02:40
duplicate of #37

**Closed by thejinx0r** 2015-01-07 02:40 UTC
