### ISSUE TITLE
client.coffee gone from the repository

### ISSUE THREAD

**Issue by m3i58** [thejinx0r/node-gdrive-fuse#71] opened 2015-09-06 18:06 UTC
There is client.coffee no more.

**Comment by thejinx0r** [comment] 2015-09-06 18:43
Thanks for the catch, it should have been client.es6.js in the wiki.

**Comment by thejinx0r** [comment] 2015-09-06 18:45
I read your other comment, let me know if it's not that.
I just merged the code from the dev branch to the master branch.

**Comment by m3i58** [comment] 2015-09-06 18:51
Thank you.
Unfortunately there is still something wrong.

> $ nodejs client.es6.js

>/home/user/node-gdrive-fuse/src/client.es6.js:2
const readline = require('readline');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

**Comment by thejinx0r** [comment] 2015-09-06 22:07
Actually, I just tried it with node 0.10.40 and it works just fine, but when I switch to node 0.10.37, I get the same error.
I would suggest using nvm (node version manager) to use different versions of nodejs if you need to.

**Comment by m3i58** [comment] 2015-09-06 22:20
# nodejs client.es6.js

> /home/user/node-gdrive-fuse/src/client.es6.js:2
const readline = require('readline');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
root@ubuntu:~/node-gdrive-fuse/src# node --version
v0.10.40

**Comment by thejinx0r** [comment] 2015-09-06 22:50
I must have had used the wrong tabs because I ran in to the same problem after seeing your post.

So it seems like the problem is with node itself. 
I'm using the newer features of javascript, but they aren't really all implemented in nodejs yet, including node 0.12.  I would recommend using iojs v2 or v3. 

iojs was a fork of nodejs, but they are merging back together. The next version of nodejs will be v4.

**Comment by iplor** [comment] 2015-09-22 14:41
I'm getting the same syntax error when following the current installation instructions. I'm not too familiar with this nodejs stuff - could you please give a bit more detail about what I need to do to fix this error?

**Comment by wnielson** [comment] 2015-11-09 02:32
I was having the same issue, so I installed iojs v2 and now get this error

```
/opt/node-gdrive-fuse/src/client.es6.js:119
            setImmediate( ()=> { queryDatabaseAndParseFiles(offset) } );
                           ^

SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:471:10)
    at startup (node.js:117:18)
    at node.js:951:3
```

Upgrading to iojs v3 didn't fix it (produces the same error).

**Comment by thejinx0r** [comment] 2015-11-11 19:11
I've started to use fat arrows which are only available in nodejs v4 and newer.
Can you try that?

**Comment by wnielson** [comment] 2015-11-11 19:32
That fixed it.  I removed all previous node and iojs binaries, then installed NodeJS version 4 (v4.2.2, specifically) like so (on Ubuntu):

```
curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
sudo apt-get install -y nodejs
```

**Comment by thejinx0r** [comment] 2015-11-11 20:00
I would suggest using nvm in the future.
See https://github.com/creationix/nvm

This way, you can have multiple versions and easily switch between them.

**Closed by thejinx0r** 2015-11-11 20:00 UTC
